POST http://localhost:3001/api/projects
Content-Type: application/json

{
  "name": "Markdown Previewer",
  "description": "This project is a Markdown Previewer built using React and the 'marked' library. It allows users to input Markdown text in an editor and see a live preview of the rendered HTML.",
  "url": "https://toanthanhtu.github.io/markdown-previewer/",
  "imageUrl": "https://raw.githubusercontent.com/ToanThanhTu/thanhtoantu-portfolio/refs/heads/main/frontend/src/assets/markdown-previewer.png"
}